name: Release
on:
  push:
    tags:
        - v*
    branches:
      - 'main'
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node: [18]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node Js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: npm install

      - name: Build Library
        run: |
          npm run build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #   https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
          tag: v${{github.run_number}}
        run: |
            gh release create "$tag" \
                --repo="$GITHUB_REPOSITORY" \
                --title="${tag#v}" \
                --generate-notes

      - name: Deploy
        run: |
          npm run deploy